version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_master
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "9000:9000"
