version: "3.7"
services:
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.example.com"
        # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - "80:80"
#        - "443:443"
#        - "22:22"