version: "3.7"
services:
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "user@gmail.com"
        gitlab_rails['smtp_password'] = "app-password"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "3000:80"
#     - "443:443"
#     - "22:22"