version: "3.7"
services:
  jenkins:
    build:
      context: ./jenkins/.
    container_name: jenkins_master
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
