version: "3.7"
services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar

    postgres:
      image: postgres:alpine
      container_name: postgres_db
      environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonar